version: '3.8'

services:
  # Câu 81, 83, 85: Service Backend
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://<username>:<password>@cluster0.mongodb.net/students?retryWrites=true&w=majority

  # Câu 82, 84: Service Frontend
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
