services:
  mongodb:
    image: mongo:7
    container_name: student-mongodb
    ports:
      - "27017:27017"
    volumes:
      - student-mongodb-data:/data/db

  backend:
    image: ngominhnhat/mern-backend:1.0
    container_name: mern-backend-hub
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://student-mongodb:27017/studentdb
    depends_on:
      - mongodb

  frontend:
    image: ngominhnhat/mern-frontend:2.0
    container_name: mern-frontend-hub
    ports:
      - "3000:5173"
    environment:
      VITE_API_PROXY_TARGET: http://backend:5000
    depends_on:
      - backend

volumes:
  student-mongodb-data: